before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: github-app-token
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - "-s -w"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

signs:
  - id: github-app-token-keyless
    artifacts: archive
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: ["sign-blob", "-y", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]
  - id: checksum-keyless
    artifacts: checksum
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: ["sign-blob", "-y", "--output-signature", "${artifact}-keyless.sig", "--output-certificate", "${artifact}-keyless.pem", "${artifact}"]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"

release:
  github:
    owner: fensak-io
    name: github-app-token
  mode: keep-existing
